In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\chuka\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [10]:
from numpy import array
# associated attributes of an ndarray are shape of the array, and type of the array
# shape of the array tells you about dimensionality (row/columns) while type of array tells you about data type contained

In [20]:
# create a one-dimensional array

a1 = array((1,2,3,4,5))

In [40]:
print(a1)

[1 2 3 4 5]


In [41]:
a1[3]

4

In [42]:
a1[0]

1

In [43]:
a1[2]

3

In [22]:
type(a1)

numpy.ndarray

In [24]:
print(a1+5)

[ 6  7  8  9 10]


In [26]:
a2 = array((6,7,8,9,10))

In [27]:
print(a2)

[ 6  7  8  9 10]


In [28]:
print(a1 + a2)

[ 7  9 11 13 15]


In [29]:
a3 = np.arange(15)

In [30]:
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [31]:
#first number in the arange function is the starting number, 2nd is the range and 3rd is the intervals 
a4 = np.arange(1,20,2)

In [32]:
print(a4)

[ 1  3  5  7  9 11 13 15 17 19]


In [33]:
#creating a multi dimensional array
a2d = [[1,2,3,4,5], [6,7,8,9,10]]

In [34]:
a2d = array(a2d)

In [35]:
print(a2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
type(a2d)

numpy.ndarray

In [38]:
# display number of rows and columns respectively
a2d.shape

(2, 5)

In [44]:
a2d[1,2]

8

In [45]:
a2d[:,4]

array([ 5, 10])

In [46]:
a2d_slicing = a2d[1,:]

In [47]:
a2d_slicing

array([ 6,  7,  8,  9, 10])

In [48]:
# operations using arrays
a1 + a2

array([ 7,  9, 11, 13, 15])

In [49]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [50]:
A = array([[3,2], [4,5]])

In [51]:
A

array([[3, 2],
       [4, 5]])

In [52]:
B = array([[1,2], [4,1]])

In [53]:
B

array([[1, 2],
       [4, 1]])

In [54]:
B += 2

In [55]:
B

array([[3, 4],
       [6, 3]])

In [57]:
B.sum()

16

In [59]:
B_slice = B[1,:]

In [60]:
B_slice

array([6, 3])

In [61]:
np.logical_and(A[0,1]>A[1,0], A[1,1]<A[1,0])

False

In [64]:
index = array((1,2,3,4,5,6,7))
a = array((np.nan, np.nan, np.nan, 0.1, 0.1, 0.1, 0.1))
b = array((0.2, np.nan, 0.2, 0.2, 0.2, np.nan, np.nan))
c = array((np.nan, 0.5, 0.5, np.nan, 0.5, 0.5, np.nan))

In [65]:
import pandas as pd

In [66]:
df = pd.DataFrame({'A':a, 'B':b, 'C':c}, index = index)

In [67]:
df

A    B    C
1  NaN  0.2  NaN
2  NaN  NaN  0.5
3  NaN  0.2  0.5
4  0.1  0.2  NaN
5  0.1  0.2  0.5
6  0.1  NaN  0.5
7  0.1  NaN  NaN

In [68]:
df.to_numpy()

array([[nan, 0.2, nan],
       [nan, nan, 0.5],
       [nan, 0.2, 0.5],
       [0.1, 0.2, nan],
       [0.1, 0.2, 0.5],
       [0.1, nan, 0.5],
       [0.1, nan, nan]])